#!/bin/python

import sys


		      
fib=[]

t = int(raw_input().strip())
for a0 in xrange(t):
    b=[]
    n = long(raw_input().strip())
    if(t>=1 and t<=10**5 and n>=10 and n<=(4*10**16)):
       # fib=[0,1]
       # for i in range(2,n):
       #     fib.insert(i,(fib[i-1]+fib[i-2]))
       #     if(fib[i]%2==0 and fib[i]<n):
       #         b.append(fib[i])
       # print(sum(b))
        f1 = 1
        f2 = 2
        f = 0
        sum = 0
        while(f1 < n):
        
            if(f1 % 2 == 0):
            
                sum += f1
            
            f = f1 + f2
            f1 = f2
            f2 = f
        print sum
        
        
    
   
    
    
